### PR TITLE
updates to build with template-haskell 2.16 and 2.17

### PR DESCRIPTION
**Pull request by byorgey**
With this patch, seems to build fine with GHC 8.10 and 9.0, though I am not sure how to test it.

### CODE REVIEW

**Comment by byorgey** [comment]
Oops, closing in favor of #9 .

**Comment by byorgey** [comment]
Actually, I am reopening this.  I noticed that this patch uses CPP to support multiple versions of template-haskell, whereas #9 only builds on GHC 9.0 + template-haskell-2.17.

**Comment by wenkokke** [comment]
@JonasDuregard please merge this PR and release a new version.

(Also, maybe consider moving these packages to an organisation, and giving shared ownership and ability to publish to Hackage to several other members?)

**Comment by L-as** [comment]
This works with TH 2.18 too FWIW

**Comment by byorgey** [comment]
@JonasDuregard I would be happy to help maintain this library if you no longer have time.

**Comment by wenkokke** [comment]
@byorgey I think Jonas doesn’t get GitHub notifications, but you can find his email on his Chalmers page.

**Comment by byorgey** [comment]
@wenkokke Yes, I sent him an email too.  I also emailed him last year with no response.  If he doesn't respond again, within, say, a week from now, I plan to start the process to take over maintainership of the `size-based` and `testing-feat` packages on Hackage.  I'd be happy to have you (or anyone else) as a co-maintainer if you like.

**Comment by wenkokke** [comment]
Would be happy to!

**Comment by Daniel-Diaz** [comment]
I also found myself unable to build this package against Stackage LTS-19.0 because of this.

**Comment by teto** [comment]
a week has passed I think :) thanks for the diagrams library btw.

**Comment by byorgey** [comment]
@teto Yes, I did indeed initiate the package maintainership takeover process one week after posting that comment, and the process just concluded a few days ago, so I now have access to upload these packages to Hackage.  @wenkokke and I will need to coordinate to figure out where we are going to host repositories, etc., but you can expect to see some updated versions of these packages uploaded to Hackage soon!

**Comment by teto** [comment]
something I've never understood in haskell is the need to put upper bounds.
With ghc 9.2.1 I get
```
 cabal build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: size-based-0.1.2.0 (user goal)
[__1] next goal: template-haskell (dependency of size-based)
[__1] rejecting: template-haskell-2.18.0.0/installed-2.18.0.0 (conflict:
size-based => template-haskell>=2.5 && <2.16)
[__1] skipping: template-haskell-2.18.0.0, template-haskell-2.17.0.0,
template-haskell-2.16.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=2.5 && <2.16' from
'size-based')
[__1] rejecting: template-haskell-2.15.0.0, template-haskell-2.14.0.0,
template-haskell-2.13.0.0, template-haskell-2.12.0.0,
template-haskell-2.11.1.0, template-haskell-2.11.0.0,
template-haskell-2.10.0.0, template-haskell-2.9.0.0, template-haskell-2.8.0.0,
template-haskell-2.7.0.0, template-haskell-2.6.0.0, template-haskell-2.5.0.0,
template-haskell-2.4.0.1, template-haskell-2.4.0.0, template-haskell-2.3.0.1,
template-haskell-2.3.0.0, template-haskell-2.2.0.0 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: size-based, template-haskell)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: template-haskell, size-based
```
If I increase the upper bound for template haskell, it compiles fine. I thought I would share in case you plan for a new release.

**Comment by byorgey** [comment]
Closing in favor of https://github.com/size-based/size-based/pull/1 .  @wenkokke and I have taken over maintainership of this package and will be using the fork at https://github.com/size-based/size-based .

**Comment by byorgey** [comment]
I just uploaded version 0.1.3.0 to Hackage, with support for GHC 8.6 through 9.2: https://hackage.haskell.org/package/size-based-0.1.3.0 .  New releases of `lazy-search` and `testing-feat` will follow shortly.

**Comment by teto** [comment]
thanks for taking care of that :100:

**Pull request closed without merging**
